[package]
name = "backend"
version = "0.1.0"
authors = ["simplyahmazing <ahmad19526@gmail.com>"]

[dependencies]
diesel = "1.3.2"
dotenv = "0.9.0"
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"